/**
 * Disposable / temporary email domain blocklist.
 *
 * Zero-latency Set lookup — no DNS, no API calls.
 * Covers the most widely-used throwaway-email services.
 * Add new domains as they appear in abuse reports.
 */

const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  // ── Major throwaway services ──────────────────────────────
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmailo.com",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
  "guerrillamail.de", "guerrillamailblock.com", "grr.la",
  "sharklasers.com", "guerrillamail.info",
  "mailinator.com", "mailinator.net", "mailinator2.com",
  "maildrop.cc", "maildrop.gq",
  "yopmail.com", "yopmail.fr", "yopmail.net", "yopmail.gq",
  "throwaway.email", "throwaway.cc",
  "dispostable.com", "disposemail.com",
  "trashmail.com", "trashmail.me", "trashmail.net", "trashmail.org",
  "trashmail.io", "trashmail.ws",
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "10minutemail.co.za", "10minemail.com",
  "minutemail.com", "minuteinbox.com",
  "tempail.com", "tempr.email", "tempmailer.com",
  "emailondeck.com",
  "getnada.com", "getnada.cc",
  "mailnesia.com",
  "mohmal.com", "mohmal.im", "mohmal.in",
  "fakeinbox.com", "fakemail.net",
  "mailcatch.com",
  "mytemp.email", "mytempmail.com",
  "getairmail.com",
  "burnermail.io",
  "inboxkitten.com",
  "discard.email",
  "harakirimail.com",
  "spamgourmet.com", "spamgourmet.net",
  "mailnull.com",
  "spamhereplease.com",
  "mailexpire.com",
  "tempinbox.com",
  "bugmenot.com",
  "binkmail.com",
  "safetymail.info",
  "incognitomail.org", "incognitomail.com",
  "anonymbox.com",
  "emkei.cz",
  "crazymailing.com",
  "deadaddress.com",
  "e4ward.com",
  "emailsensei.com",
  "eyepaste.com",
  "filzmail.com",
  "imails.info",
  "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
  "kasmail.com",
  "mailblocks.com",
  "mailforspam.com",
  "mailmoat.com",
  "mailshell.com",
  "meltmail.com",
  "neverbox.com",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.xl.cx",
  "oneoffemail.com",
  "pookmail.com",
  "recode.me",
  "short.cr",
  "sneakemail.com",
  "sogetthis.com",
  "spambob.com", "spambob.net", "spambob.org",
  "spaml.com", "spaml.de",
  "spamstack.net",
  "tempemail.co.za", "tempemail.net",
  "tempsky.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "trash-mail.at", "trash-mail.com",
  "tradermail.info",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org",
  "willhackforfood.biz",
  "yolanda.com",
  "zippymail.info",
  // ── Additional popular disposables ────────────────────────
  "mailsac.com", "mailsac.dev",
  "mailnator.com",
  "tempmailaddress.com",
  "emailfake.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  "armyspy.com",
  "tafmail.com",
  "20minutemail.com", "20minutemail.it",
  "33mail.com",
  "anonbox.net",
  "boun.cr",
  "devnullmail.com",
  "dingbone.com",
  "dodgit.com",
  "dodgeit.com",
  "fastacura.com",
  "flyspam.com",
  "imstations.com",
  "klzlk.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "mailin8r.com",
  "mailquack.com",
  "mailscrap.com",
  "mailzilla.com",
  "nomail2me.com",
  "no-spam.ws",
  "nospam.ze.tc",
  "owlpic.com",
  "proxymail.eu",
  "rcpt.at",
  "reallymymail.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "s0ny.net",
  "safe-mail.net",
  "safetypost.de",
  "shieldedmail.com",
  "slaskpost.se",
  "spam4.me",
  "spamavert.com",
  "spamex.com",
  "spamfree24.org",
  "spamhole.com",
  "spamobox.com",
  "tempomail.fr",
  "temporaryemail.net", "temporaryemail.us",
  "temporarymailaddress.com",
  "temporarymail.org",
  "thanksnospam.info",
  "trashemail.de",
  "trashymail.com", "trashymail.net",
  "turual.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "veryreallyme.com",
  "vidchart.com",
  "wimsg.com",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "wwwnew.eu",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xoxy.net",
  "yapped.net",
  "yep.it",
  "yuurok.com",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zoemail.org",
  // ── India-popular throwaways ──────────────────────────────
  "tempmail.in", "tempmail.co.in",
  "mailtemp.in",
  "fakemailgenerator.com",
  "emailtemp.org",
  "mail-temp.com",
  "temp-mail.de",
  "tempemails.io",
]);

/**
 * Returns true if the email uses a known disposable/temporary domain.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes("@")) return false;
  const domain = email.split("@")[1]?.toLowerCase().trim();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}

/**
 * Returns a user-friendly rejection message.
 */
export const DISPOSABLE_EMAIL_ERROR =
  "Temporary or disposable email addresses are not allowed. Please use your personal or work email to create an account.";
